### ISSUE TITLE
Replace data set report error

### ISSUE THREAD

**Issue by zhaoxiuzhu** [Valdecy/C4.5#2]
I would like to ask that I changed the data in the data file by using the Iris data set in the UCI database.After the change, I ran the program and got the following error. You should be familiar with your own code, could you help me solve it?thank you
![image](https://user-images.githubusercontent.com/77867514/115727562-4744d200-a3b6-11eb-8ea4-d3ed06b69f25.png)

**Comment by Valdecy** [comment]
Hello! The iris dataset should be a Pandas Dataframe and not a Numpy Array. This should solve the issue
